AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MutableConstant:
  Enabled: false

Style/Semicolon:
  Enabled: false
