AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GlobalVars:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
