AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MutableConstant:
  Enabled: false
